/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SubmittalsRouteImport } from './routes/submittals'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RfisRouteImport } from './routes/rfis'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HazcomRouteImport } from './routes/hazcom'
import { Route as TrailerInspectionsRouteImport } from './routes/trailer-inspections'
import { Route as HandbookFormsRouteImport } from './routes/handbook-forms'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittalsRoute = SubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RfisRoute = RfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HazcomRoute = HazcomRouteImport.update({
  id: '/hazcom',
  path: '/hazcom',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailerInspectionsRoute = TrailerInspectionsRouteImport.update({
  id: '/trailer-inspections',
  path: '/trailer-inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookFormsRoute = HandbookFormsRouteImport.update({
  id: '/handbook-forms',
  path: '/handbook-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/incidents': typeof IncidentsRoute
  '/hazcom': typeof HazcomRoute
  '/handbook-forms': typeof HandbookFormsRoute
  '/policies': typeof PoliciesRoute
  '/maintenance': typeof MaintenanceRoute
  '/inspections': typeof InspectionsRoute
  '/trailer-inspections': typeof TrailerInspectionsRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchasing': typeof PurchasingRoute
  '/rfis': typeof RfisRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submittals': typeof SubmittalsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/incidents': typeof IncidentsRoute
  '/hazcom': typeof HazcomRoute
  '/handbook-forms': typeof HandbookFormsRoute
  '/policies': typeof PoliciesRoute
  '/maintenance': typeof MaintenanceRoute
  '/inspections': typeof InspectionsRoute
  '/trailer-inspections': typeof TrailerInspectionsRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchasing': typeof PurchasingRoute
  '/rfis': typeof RfisRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submittals': typeof SubmittalsRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bids': typeof BidsRoute
  '/incidents': typeof IncidentsRoute
  '/hazcom': typeof HazcomRoute
  '/handbook-forms': typeof HandbookFormsRoute
  '/policies': typeof PoliciesRoute
  '/maintenance': typeof MaintenanceRoute
  '/inspections': typeof InspectionsRoute
  '/trailer-inspections': typeof TrailerInspectionsRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchasing': typeof PurchasingRoute
  '/rfis': typeof RfisRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submittals': typeof SubmittalsRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bids'
    | '/incidents'
    | '/hazcom'
    | '/handbook-forms'
    | '/policies'
    | '/maintenance'
    | '/inspections'
    | '/trailer-inspections'
    | '/procurement'
    | '/projects'
    | '/purchase-orders'
    | '/purchasing'
    | '/rfis'
    | '/schedule'
    | '/sitemap.xml'
    | '/submittals'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bids'
    | '/incidents'
    | '/hazcom'
    | '/handbook-forms'
    | '/policies'
    | '/maintenance'
    | '/inspections'
    | '/trailer-inspections'
    | '/procurement'
    | '/projects'
    | '/purchase-orders'
    | '/purchasing'
    | '/rfis'
    | '/schedule'
    | '/sitemap.xml'
    | '/submittals'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bids'
    | '/incidents'
    | '/hazcom'
    | '/handbook-forms'
    | '/policies'
    | '/maintenance'
    | '/inspections'
    | '/trailer-inspections'
    | '/procurement'
    | '/projects'
    | '/purchase-orders'
    | '/purchasing'
    | '/rfis'
    | '/schedule'
    | '/sitemap.xml'
    | '/submittals'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BidsRoute: typeof BidsRoute
  IncidentsRoute: typeof IncidentsRoute
  HazcomRoute: typeof HazcomRoute
  HandbookFormsRoute: typeof HandbookFormsRoute
  PoliciesRoute: typeof PoliciesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  InspectionsRoute: typeof InspectionsRoute
  TrailerInspectionsRoute: typeof TrailerInspectionsRoute
  ProcurementRoute: typeof ProcurementRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  PurchasingRoute: typeof PurchasingRoute
  RfisRoute: typeof RfisRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmittalsRoute: typeof SubmittalsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submittals': {
      id: '/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof SubmittalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfis': {
      id: '/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof RfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazcom': {
      id: '/hazcom'
      path: '/hazcom'
      fullPath: '/hazcom'
      preLoaderRoute: typeof HazcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailer-inspections': {
      id: '/trailer-inspections'
      path: '/trailer-inspections'
      fullPath: '/trailer-inspections'
      preLoaderRoute: typeof TrailerInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook-forms': {
      id: '/handbook-forms'
      path: '/handbook-forms'
      fullPath: '/handbook-forms'
      preLoaderRoute: typeof HandbookFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BidsRoute: BidsRoute,
  IncidentsRoute: IncidentsRoute,
  HazcomRoute: HazcomRoute,
  HandbookFormsRoute: HandbookFormsRoute,
  PoliciesRoute: PoliciesRoute,
  MaintenanceRoute: MaintenanceRoute,
  InspectionsRoute: InspectionsRoute,
  TrailerInspectionsRoute: TrailerInspectionsRoute,
  ProcurementRoute: ProcurementRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  PurchasingRoute: PurchasingRoute,
  RfisRoute: RfisRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmittalsRoute: SubmittalsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
